### ISSUE TITLE
EOF exception when parsing map string

### ISSUE THREAD

**Issue by kennyjwilli** [clj-commons/rewrite-cljs#11] opened 2017-09-01 22:41 UTC
I am getting this exception when attempting to parse a map string. 
```clojure
(require '[rewrite-clj.parser :as rewrite-parser])

(rewrite-parser/parse-string "{:a \"a\"}")

Error: [line 1, col 3] Unexpected EOF while reading start of :.
    at new cljs$core$ExceptionInfo (/home/kenny/lumo-cljfmt/out/.cljs_node_repl/cljs/core.js:35343:10)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/home/kenny/lumo-cljfmt/out/.cljs_node_repl/cljs/core.js:35404:9)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/home/kenny/lumo-cljfmt/out/.cljs_node_repl/cljs/core.js:35400:26)
    at cljs$core$ex_info (/home/kenny/lumo-cljfmt/out/.cljs_node_repl/cljs/core.js:35386:26)
    at Function.cljs.tools.reader.impl.errors.throw_ex.cljs$core$IFn$_invoke$arity$variadic (/home/kenny/lumo-cljfmt/.cljs_node_repl/cljs/tools/reader/impl/errors.js:53:25)
    at cljs$tools$reader$impl$errors$throw_ex (/home/kenny/lumo-cljfmt/.cljs_node_repl/cljs/tools/reader/impl/errors.js:35:47)
    at Function.cljs.tools.reader.impl.errors.eof_error.cljs$core$IFn$_invoke$arity$variadic (/home/kenny/lumo-cljfmt/.cljs_node_repl/cljs/tools/reader/impl/errors.js:163:47)
    at cljs$tools$reader$impl$errors$eof_error (/home/kenny/lumo-cljfmt/.cljs_node_repl/cljs/tools/reader/impl/errors.js:159:48)
    at cljs$tools$reader$impl$errors$throw_eof_at_start (/home/kenny/lumo-cljfmt/.cljs_node_repl/cljs/tools/reader/impl/errors.js:217:48)
    at cljs$tools$reader$read_token (/home/kenny/lumo-cljfmt/.cljs_node_repl/cljs/tools/reader.js:47:57)
```

If I run this same code with [rewrite-clj](https://github.com/xsc/rewrite-clj) I get this: 

```clojure
(rewrite-parser/parse-string "{:a \"a\"}")
=> <map: {:a "a"}>
```

**Comment by bhurlow** [comment] 2017-09-03 22:26
@kennyjwilli @rundis It appears there may be a bug in keyword parsing:

```
(p/parse-string ":testkw")
[line 1, col 2] Unexpected EOF while reading start of :.
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:1922:449)
	 Function.cljs.tools.reader.impl.errors.throw_ex.cljs$core$IFn$_invoke$arity$variadic (evalmachine.<anonymous>:53:25)
	 Function.cljs.tools.reader.impl.errors.eof_error.cljs$core$IFn$_invoke$arity$variadic (evalmachine.<anonymous>:163:47)
	 (Object.cljs$tools$reader$impl$errors$throw_eof_at_start)
	 cljs.tools.reader.read_token (NO_SOURCE_FILE <embedded>:2171:94)
	 rewrite_clj$reader$read_keyword (evalmachine.<anonymous>:331:40)
	 rewrite_clj$parser$keyword$parse_keyword (evalmachine.<anonymous>:14:80)
	 rewrite_clj$reader$read_with_meta (evalmachine.<anonymous>:252:21)
```

**Comment by bhurlow** [comment] 2017-09-03 22:30
@kennyjwilli are you testing this using `lumo`?  That's where it seems to be failing for me

**Comment by bhurlow** [comment] 2017-09-03 22:34
using lumo with version `0.3.1` works ok:

```
lumo -D rewrite-cljs:0.3.1
```

looks like it could be an issue with the cljs reader version

**Comment by kennyjwilli** [comment] 2017-09-04 18:04
I was actually testing it in a NodeJS REPL with the latest version of CLJS (1.9.908).

**Comment by kennyjwilli** [comment] 2017-09-05 20:45
I tried using CLJS v1.7.228 and am still receiving the same error.

**Comment by kennyjwilli** [comment] 2017-09-05 20:53
Actually I just realized in my test there was an implicit version of the reader set. Using v1.7.228 works as expected. This means this issue is definitely due to a change in tools.reader. rewrite-cljs is using 1.0.0-alpha3 when the latest version of the reader is 1.0.5: https://github.com/clojure/tools.reader/blob/master/CHANGELOG.md.

**Comment by kennyjwilli** [comment] 2017-09-05 20:57
I have worked it down to the breaking change occurring when upgrading tools.reader from v1.0.1 to v1.0.2: https://github.com/clojure/tools.reader/compare/tools.reader-1.0.1...tools.reader-1.0.2.

**Comment by kkinnear** [comment] 2017-10-01 21:56
Yes, `rewrite-cljs` now does not work in `lumo`.  The problem is that `rewrite-clj.reader/read-keyword` calls `cljs.tools.reader/read-token`, which is defined with `defn-`.  A breaking change was introduced in `read-token` in some version prior to `1.0.5` but after `1.0.0-alpha3`.  In addition, the `reader-error` function has moved to `cljs.tools.reader.impl.errors/reader-error`.  Adding `:keyword` to the call to `read-token`, and fixing the location of `reader-error`, appears to fix this problem (at least some things work).  I have not done significant testing on this fix.  For what it is worth, here is what I have tried that seems to work in my use case:
```clojure
(ns rewrite-clj.reader)
  
(defn read-keyword
  [^not-native reader initch]
  (let [tok (cljs.tools.reader/read-token reader :keyword (read-char reader))
        a (re-matches* (re-pattern "^[:]?([^0-9/].*/)?([^0-9/][^/]*)$") tok)
        token (aget a 0)
        ns (aget a 1)
        name (aget a 2)]
    (if (or (and (not (undefined? ns))
                 (identical? (. ns
                                (substring (- (.-length ns) 2) (.-length ns)))
                             ":/"))
            (identical? (aget name (dec (.-length name))) ":")
            (not (== (.indexOf token "::" 1) -1)))
      (cljs.tools.reader.impl.errors/reader-error reader
                                                  "Invalid token: "
                                                  token)
      (if (and (not (nil? ns)) (> (.-length ns) 0))
        (keyword (.substring ns 0 (.indexOf ns "/")) name)
        (keyword (.substring token 1))))))
```
The only changes are to the call to `read-token` and the location of `reader-error`, though I probably reformatted the whole function for clarity on my part.  Were you to use this, you would obviously want to remove the `(def reader-error ...)` from earlier in the file.

It would sure be nice to get an updated `rewrite-cljs` that would work with the current `tools.reader`!  I rely on `rewrite-cljs`, and I have at least one user who uses `lumo` and has been stopped by this problem.

**Comment by rundis** [comment] 2017-10-09 21:36
@kkinnear Feel free to close this issue if this solves your problem! Haven't been doing much clojure/clojurescript lately, but I'll try to find time to review pr's from time to time. Cheers for your contribution.

**Comment by kkinnear** [comment] 2017-10-10 02:58
Yes, thanks for the quick response!  `[rewrite-cljs "0.4.4"]` now works great with both lumo 1.8-beta and planck 2.8.1, and parses things with keywords correctly.  Thanks for doing rewrite-cljs -- other than this one issue, it has worked flawlessly for me.  

I would certainly consider this issue closed -- and I would close it, except that I don't seem to have a button to do so.  Possibly because I didn't open the issue.  It would be good if you closed the issue.

**Closed as completed** 2017-10-24 18:16 UTC
